### ISSUE TITLE
Configure for CI/CD

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/iframely#1]
(Deadline 8/7/2020)

See Docs:
https://github.com/PRX/Infrastructure/tree/master/ci#continuous-integration-support
https://github.com/PRX/Infrastructure/tree/master/cd#on-boardings-applications-and-services

**Comment by farski** [comment]
@rpeterman-gp Let me know if/how you want to split this up. The CD work should probably get a ticket in the Infrastructure repo, since all the work needs to happen there.

**Comment by rpeterman-gp** [comment]
@farski Set up a ticket in Infrastructure PRX/Infrastructure#419
